name: Build All
on: [workflow_dispatch]
jobs:
  build_android:
    uses: ./.github/workflows/build_android.yml
  build_ios:
    uses: ./.github/workflows/build_ios.yml
  build_ubuntu_2204:
    uses: ./.github/workflows/build_ubuntu_2204.yml
  build_osx:
    uses: ./.github/workflows/build_osx.yml
  build_windows:
    uses: ./.github/workflows/build_windows.yml
