name: Test All
on: [workflow_dispatch]
jobs:
  test_ubuntu_2204:
    uses:  ./.github/workflows/test_ubuntu_2204.yml
    secrets: inherit
  test_osx:
    uses:  ./.github/workflows/test_osx.yml
    secrets: inherit
  test_windows:
    uses:  ./.github/workflows/test_windows.yml
    secrets: inherit
